### ISSUE TITLE
nav bar logo not mobile friendly

### ISSUE THREAD

**Issue by danbjoseph** [civictechdc/codefordc-website#47]
it overflows the top bar and overlaps with page content
<img src="https://github.com/codefordc/codefordc-website/assets/4806884/591fec0c-45f5-4b57-95ad-932da2aca985" width=50% height=50%>

**Comment by GameDevDebbie** [comment]
I am researching a solution.
It seems to relate to Trello card: 
"Fix the alignment of the content on the Mobile Screen size version of the "Donate" page":
https://trello.com/c/d0pDc90K

**Comment by NickSto** [comment]
FYI I prototyped a fix for this in PR #55, but #60 is blocking that particular PR from working at the moment.

**Comment by NickSto** [comment]
Update: #66 will fix this
