### ISSUE TITLE
outdated email needs replacing

### ISSUE THREAD

**Issue by danbjoseph** [civictechdc/codefordc-website#54]
team@codefordc.org email address is referenced a few places. is there an email to replace it?

https://github.com/civictechdc/codefordc-website/blob/0d84d30a33eaace06de336654788b97769410e74/code-of-conduct.md?plain=1#L54
https://github.com/civictechdc/codefordc-website/blob/0d84d30a33eaace06de336654788b97769410e74/code-of-conduct.md?plain=1#L72
https://github.com/civictechdc/codefordc-website/blob/0d84d30a33eaace06de336654788b97769410e74/index.html#L196

**Comment by GameDevDebbie** [comment]
Yes, we have a new email address. I have tested and confirmed that it is active: [team@civictechdc.org](mailto:team@civictechdc.org).
I will make the flagged updates and submit a commit/PR.
Please flag any other locations.
Thank you.
